config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index'
  get '/tasks/new', to: 'tasks#new', as: :tasks_new
  get '/tasks/:id', to: 'tasks#show', as: :task
  post '/tasks', to: 'tasks#create'
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch '/tasks/:id', to: 'tasks#update'

  delete '/tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
<p>
<%= f.label :title %>
</p>
<p>
<%= f.text_field :title%>
</p>
<p>
<%= f.label :details %>
</p>
<p>
<%= f.text_field :details %>
</p>
<%= f.label :completed %>
<p>
<%= f.text_field :completed %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= render "form" %>

app/views/tasks/index.html.erb
<h1>All tasks</h1>

  <% @tasks.each do |task| %>
    <p>
    	<% if task.completed %>
    	  <i class="fa fa-check-square-o"></i>
    	  <%= link_to task.title, task_path(task) %> 
    	<% else %>
    	  <i class="fa fa-square-o"></i>
    	  <%= link_to task.title, task_path(task) %>
    	<% end %>
    </p>
  <% end %>

  <h4><%= link_to "Add a new task", tasks_new_path %></h4>

 
 

app/views/tasks/new.html.erb
<h1>Create a new task</h1>
<%= render "form" %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<%= link_to "Back to tasks", tasks_path %>
<%= link_to "Edit a task", edit_path %>
<%= link_to "Destroy", task_path(@task), method: :delete, data: {confirm: "Are you sure?"} %>